version: '3.8'

services:
  dashboard:
    build:
      context: .
      args:
        APP_NAME: 'dashboard'
        CONFIGURATION: 'testing'
        BASE_HREF: 'dashboard'
    container_name: dashboard
  login:
    build:
      context: .
      args:
        APP_NAME: 'login'
        CONFIGURATION: 'testing'
        BASE_HREF: 'login'

    container_name: login
  gateway:
    image: nginx:1.22.0-alpine
    ports:
      - '80:80'
    volumes:
      - ./gateway.nginx.conf:/etc/nginx/conf.d/default.conf
    links:
      - dashboard
      - login
